In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("credit_risk_project_dataset.csv")

In [3]:
df.head()

,customer_id,age,income,region,account_type,loan_type,account_open_date,balance,days_past_due,monthly_payment,credit_limit,status,bucket
0,1,23,63527,East,Credit Card,Mortgage,2017-01-18,421988,35,7513,481031,Delinquent,30-60
1,2,49,45827,East,Current,Auto Loan,2022-01-15,197938,95,4391,286382,Charged-off,90+
2,3,55,76476,North,Loan,Personal Loan,2019-12-04,222253,120,21034,335671,Charged-off,90+
3,4,59,118912,South,Loan,Credit Card,2022-02-07,38958,35,42379,188862,Delinquent,30-60
4,5,38,126580,West,Savings,Personal Loan,2023-11-22,268200,0,38754,322395,Current,Current

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2000 non-null   int64
 1   age                2000 non-null   int64
 2   income             2000 non-null   int64
 3   region             2000 non-null   str
 4   account_type       2000 non-null   str
 5   loan_type          2000 non-null   str
 6   account_open_date  2000 non-null   str
 7   balance            2000 non-null   int64
 8   days_past_due      2000 non-null   int64
 9   monthly_payment    2000 non-null   int64
 10  credit_limit       2000 non-null   int64
 11  status             2000 non-null   str
 12  bucket             2000 non-null   str
dtypes: int64(7), str(6)
memory usage: 294.0 KB

In [5]:
df.describe()

,customer_id,age,income,balance,days_past_due,monthly_payment,credit_limit
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,42.436000,112528.256000,406667.853500,28.485000,24915.812000,261743.694000
std,577.494589,12.563193,49656.774123,230339.767779,34.591589,14228.802215,135900.975794
min,1.000000,21.000000,25140.000000,5233.000000,0.000000,1002.000000,20357.000000
25%,500.750000,32.000000,69926.750000,205912.750000,0.000000,12419.250000,149497.000000
50%,1000.500000,42.500000,113602.000000,401883.500000,10.000000,24706.500000,260065.500000
75%,1500.250000,53.000000,155358.500000,609069.000000,50.000000,37224.750000,377055.000000
max,2000.000000,64.000000,199945.000000,799823.000000,120.000000,49978.000000,499637.000000

In [6]:
df.isnull().sum()

customer_id          0
age                  0
income               0
region               0
account_type         0
loan_type            0
account_open_date    0
balance              0
days_past_due        0
monthly_payment      0
credit_limit         0
status               0
bucket               0
dtype: int64

In [7]:
df['account_open_date']=pd.to_datetime(df['account_open_date'])

In [8]:
#lamda x function is used for check every value of x =days_past_due values
df['risk_flag']=df['days_past_due'].apply(lambda x: 'bad' if x>60 else 'good')

In [9]:
#Categorizes customers into:High risk,Medium risk,Low risk
def risk_catagory(x):
    if x>60:
        return "High"
    elif x>30:
        return "medium"
    else:
        return "low"
df['risk_catagory']=df['days_past_due'].apply(risk_catagory)

In [10]:
# Calculates how long customer is with bank
df['vintage_days']=(pd.to_datetime('today')-df['account_open_date']).dt.days

In [11]:
#if balance is 500 and limit=1000 So, 500/1000=0.5=50% (utilization=50%)
#High utilization → high risk
df['utilization']=df['balance']/df['credit_limit']

In [12]:
df.head()

,customer_id,age,income,region,account_type,loan_type,account_open_date,balance,days_past_due,monthly_payment,credit_limit,status,bucket,risk_flag,risk_catagory,vintage_days,utilization
0,1,23,63527,East,Credit Card,Mortgage,2017-01-18,421988,35,7513,481031,Delinquent,30-60,good,medium,3384,0.877257
1,2,49,45827,East,Current,Auto Loan,2022-01-15,197938,95,4391,286382,Charged-off,90+,bad,High,1561,0.691168
2,3,55,76476,North,Loan,Personal Loan,2019-12-04,222253,120,21034,335671,Charged-off,90+,bad,High,2334,0.662116
3,4,59,118912,South,Loan,Credit Card,2022-02-07,38958,35,42379,188862,Delinquent,30-60,good,medium,1538,0.206278
4,5,38,126580,West,Savings,Personal Loan,2023-11-22,268200,0,38754,322395,Current,Current,good,low,885,0.831899

In [14]:
df.describe()

,customer_id,age,income,account_open_date,balance,days_past_due,monthly_payment,credit_limit,vintage_days,utilization
count,2000.000000,2000.000000,2000.000000,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,42.436000,112528.256000,2021-01-30 02:50:38.400000,406667.853500,28.485000,24915.812000,261743.694000,1910.881500,2.596286
min,1.000000,21.000000,25140.000000,2017-01-03 00:00:00,5233.000000,0.000000,1002.000000,20357.000000,403.000000,0.014139
25%,500.750000,32.000000,69926.750000,2019-01-14 18:00:00,205912.750000,0.000000,12419.250000,149497.000000,1166.750000,0.809675
50%,1000.500000,42.500000,113602.000000,2021-02-04 12:00:00,401883.500000,10.000000,24706.500000,260065.500000,1905.500000,1.545633
75%,1500.250000,53.000000,155358.500000,2023-02-13 06:00:00,609069.000000,50.000000,37224.750000,377055.000000,2657.250000,2.774716
max,2000.000000,64.000000,199945.000000,2025-03-18 00:00:00,799823.000000,120.000000,49978.000000,499637.000000,3399.000000,36.777439
std,577.494589,12.563193,49656.774123,NaN,230339.767779,34.591589,14228.802215,135900.975794,868.335748,3.593096

In [15]:
df.to_csv("credit_risk_analysis_final_dataset",index=False)
print("file saved")

file saved

In [16]:
df=pd.read_csv('credit_risk_analysis_final_dataset')

In [17]:
df.to_csv('credit_risk_analysis_final_dataset.csv',index=False)
print("done! File saveed with.csv")

done! File saveed with.csv

In [18]:
import os
files=os.listdir(os.getcwd())
for f in files:
    print (f)

credit_risk_analysis_final_dataset
credit_risk_analysis_final_dataset.csv
credit_risk_project_dataset.csv
My_banking_project_analysis.ipynb
my_banking_project_anlysis_part2.ipynb