In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
df=pd.read_csv("my_final_credit_risk_dataset_after_edit_on_sql_phase 2.csv")

In [20]:
df['bucket'].value_counts() # it will count the value how many times appears.

bucket
Current    385
30-60      218
0-30       200
60-90      100
90+         97
Name: count, dtype: int64

In [21]:
df.groupby('bucket')['balance'].sum

In [22]:
high_risk= df[df['risk_level']=='High'] #Filters only high-risk customers

In [23]:
df.groupby('risk_level')['balance'].sum() #Calculates total money in each risk category

risk_level
High       78063262
low       243820872
medium     90031229
Name: balance, dtype: int64

In [24]:
df.groupby('loan_type')['days_past_due'].mean() #it will calculate avg days_past_due mean on every loan type

loan_type
Auto Loan        32.644444
Credit Card      30.402299
Mortgage         27.988506
Personal Loan    29.229249
Name: days_past_due, dtype: float64

In [25]:
df['utilization']=df['balance']/df['credit_limit'] #Calculates % of credit used

In [26]:
charged_off=df[df['status']=='charged_off'] ['balance'].sum()
total_balance = df['balance'].sum()

recovery_rate = charged_off / total_balance

In [28]:
def collection_strategy(x):
    if x == 'High':
        return 'Aggressive'
    elif x == 'Medium':
        return 'Moderate'
    else:
        return 'Soft'

df['collection_strategy'] = df['risk_level'].apply(collection_strategy) #Assigns strategy to each customer

In [29]:
df.sort_values(by='balance', ascending=False).head() #Shows customers with highest balance,“Which customers can cause biggest loss?”

,cust_id,age,income,region,account_type,loan_type,account_open_date,balance,days_past_due,monthly_payment,credit_limit,status,bucket,risk_flag,risk_level,vintage_days,utilization,collection_strategy
512,513,41,77585,West,Current,Personal Loan,2022-01-14,799823,20,5983,306753,Delinquent,0-30,good,low,1560,2.607384,Soft
89,90,35,29851,North,Current,Auto Loan,2017-12-08,798549,20,6578,467221,Delinquent,0-30,good,low,3058,1.709146,Soft
117,118,59,62842,West,Loan,Credit Card,2020-04-21,798053,35,35534,407836,Delinquent,30-60,good,medium,2193,1.956799,Soft
339,340,23,99977,East,Current,Credit Card,2021-11-17,798043,0,45738,140914,Current,Current,good,low,1618,5.663334,Soft
209,210,53,195587,East,Savings,Mortgage,2018-09-25,797129,0,8171,394506,Current,Current,good,low,2767,2.020575,Soft

In [30]:
df[df['risk_level']=='High'].sort_values(by='balance', ascending=False) #Finds high-risk + high-value customers,“Who are the most dangerous customers for the bank?”

,cust_id,age,income,region,account_type,loan_type,account_open_date,balance,days_past_due,monthly_payment,credit_limit,status,bucket,risk_flag,risk_level,vintage_days,utilization,collection_strategy
471,472,57,38375,West,Credit Card,Personal Loan,2017-08-26,791096,95,27620,190171,Charged-off,90+,bad,High,3162,4.159919,Aggressive
324,325,35,108821,East,Loan,Mortgage,2022-07-05,789698,120,7381,378632,Charged-off,90+,bad,High,1388,2.085661,Aggressive
517,518,58,55054,South,Loan,Mortgage,2018-04-20,785690,70,10353,350362,Charged-off,60-90,bad,High,2925,2.242509,Aggressive
392,393,46,97862,East,Savings,Personal Loan,2021-12-26,784067,120,32152,266835,Charged-off,90+,bad,High,1579,2.938396,Aggressive
659,660,61,105502,North,Loan,Auto Loan,2018-07-26,781304,70,4404,301788,Charged-off,60-90,bad,High,2828,2.588917,Aggressive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,747,36,36183,East,Credit Card,Auto Loan,2020-03-03,37065,70,44509,475797,Charged-off,60-90,bad,High,2242,0.077901,Aggressive
677,678,64,109427,South,Savings,Credit Card,2023-07-10,32591,120,6706,88800,Charged-off,90+,bad,High,1018,0.367016,Aggressive
959,960,40,142747,West,Loan,Credit Card,2020-10-10,25047,70,25622,346408,Charged-off,60-90,bad,High,2021,0.072305,Aggressive
920,921,63,126219,West,Current,Personal Loan,2022-11-23,22167,120,4514,369681,Charged-off,90+,bad,High,1247,0.059963,Aggressive
647,648,22,101433,East,Savings,Auto Loan,2020-02-23,5398,70,35589,93447,Charged-off,60-90,bad,High,2251,0.057765,Aggressive

In [31]:
df.groupby('region')['days_past_due'].mean()

region
East     30.627615
North    32.727273
South    28.016194
West     28.582375
Name: days_past_due, dtype: float64

In [32]:
df.to_csv("my_banking_project_part3_final_dataset.csv", index=False)